"""'add_status_to_todo'

Revision ID: afe0d9440bb8
Revises: 54c8d6a75bc4
Create Date: 2017-08-12 23:21:57.841530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe0d9440bb8'
down_revision = '54c8d6a75bc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'status')
    # ### end Alembic commands ###
